services:
  aurora:
    build: .
    container_name: aurora-server
    restart: always
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./cache:/app/cache
